Importação das bibliotecas

In [1]:
import gensim
from gensim.models import word2vec
from gensim.models.word2vec import Word2Vec
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Módulo 2/Programação/ Dados/lematizacao.csv')
df.head()

Unnamed: 0          autor  \
0           0     v8_capital   
1           1  winthegame_of   
2           2     marta_bego   
3           3     lmviapiana   
4           4   vanilson_dos   

                                               texto sentimento  \
0  Confira os resultados dos nossos fundos no mês...    NEUTRAL   
1  A Alvarez & Marsal estará conosco no Sportainm...    NEUTRAL   
2  #Repost btgpactual with make_repost ・・・ Entend...    NEUTRAL   
3                               Minuto touro de ouro   POSITIVE   
4                                   @ricktolledo Sim    NEUTRAL   

                                              tokens  
0  ['confira', 'o', 'resultado', 'de o', 'nosso',...  
1  ['Alvarez', 'Marsal', 'estara', 'conosco', 'sp...  
2  ['repost', 'btg', 'With', 'makerepost', 'enten...  
3                        ['minuto', 'touro', 'ouro']  
4                             ['Ricktolledo', 'sim']

In [3]:
import gensim.downloader as api
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [4]:
#Printa os modelos qiue exsitem
import gensim.downloader as api
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [5]:
wv = api.load('glove-twitter-50') ##Api de exemplo com o 'glove-twitter-50'

[=================================================-] 98.1% 195.6/199.5MB downloaded


In [6]:
def sent_vec(sent):
    #Tamanho do vetor
    vector_size = wv.vector_size ##wv - modelo weord2vec treinado


    #número de elementos no vetor
    wv_res = np.zeros(vector_size)
    print(wv_res)
    ctr = 1
    
    #Condição para verificar se as palavras estão no word2vec, se sim é adicionada
    for w in sent:
        if w in wv:
            ctr += 1
            wv_res += wv[w]
    #Realiza a média. Caso queira outros resultados, mude a conta
    wv_res = wv_res/ctr

    return wv_res

In [7]:
teste = ['cachorro']
sent_vec(teste)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


array([-1.99809998e-01, -2.48925000e-01, -1.60380006e-01, -5.95000029e-01,
       -1.18555002e-01, -6.19700015e-01, -4.43619996e-01,  2.83105001e-02,
        1.92479998e-01, -5.43099999e-01, -1.43775001e-01,  1.85680002e-01,
       -1.95295006e-01, -2.34125003e-01,  1.39025003e-01,  4.54539992e-02,
       -2.76320010e-01, -3.91335011e-01,  7.41800002e-04, -7.00299978e-01,
       -1.21095002e-01,  5.01399994e-01,  3.93855006e-01, -3.61050010e-01,
        9.58199985e-03, -6.87200010e-01, -5.69549985e-02, -4.92855012e-02,
        5.06850004e-01,  2.31234998e-01,  1.89520001e-01,  8.87250006e-02,
       -1.03785001e-01, -3.61889988e-01, -7.93299973e-01,  2.26039998e-02,
       -4.31120008e-01, -3.92495006e-01, -9.66050029e-01,  1.03629997e-03,
       -7.60399997e-01, -2.69749999e-01, -6.86399996e-01, -3.19705009e-01,
       -1.16360001e-01,  4.26575005e-01,  2.51040012e-01,  2.73434997e-01,
        5.34299985e-02, -3.97044986e-01])

In [8]:
wv.similarity("cachorro", "pet")

0.34403497

In [9]:
sent_vec('cachorro')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


array([ 2.99182223e-01,  2.99110843e-03,  9.84044439e-02,  8.83088675e-03,
       -2.93010082e-02,  7.36386784e-03, -4.96343341e-01,  7.16919998e-02,
       -3.73048865e-02,  2.87727555e-01, -8.26955554e-02, -2.74464442e-01,
       -2.93776668e+00,  2.50777768e-02, -3.60423557e-01, -2.08329335e-01,
       -4.74192234e-01, -1.15034333e-01, -4.15108885e-01,  7.60177771e-01,
        1.62884224e-01, -1.34255489e-02,  3.47958886e-01,  2.29981107e-01,
        2.74055501e-02, -1.43138443e+00, -1.90018885e-01,  1.57672225e-01,
        6.68174556e-01,  6.92968885e-01,  4.51577620e-03, -4.18798335e-01,
        5.76575589e-02, -7.77956181e-03,  6.98901895e-01,  4.71606877e-01,
       -2.94909994e-01, -4.49385549e-01, -7.97514447e-01,  3.25831776e-01,
       -2.37333340e+00,  2.86845560e-01,  2.18348670e-01, -6.77727551e-02,
       -8.35778399e-04,  1.78644475e-03,  5.46722230e-02, -3.44482892e-01,
        1.88954224e-01, -7.29226672e-01])

In [10]:
teste = df['tokens'].iloc[0]

In [11]:
sent_vec(teste)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


array([ 1.96263859e-01, -8.68969600e-02,  7.82138882e-02,  1.28981825e-01,
       -1.55966235e-01,  1.33899297e-01, -4.46666371e-01,  9.34301460e-02,
       -3.33399524e-03,  5.58462260e-01, -4.84885211e-04, -8.38151716e-02,
       -3.33177512e+00,  1.85844650e-01, -3.45338613e-01, -4.02102056e-01,
       -6.13262218e-01, -7.91325272e-02, -4.59744869e-01,  3.20861662e-01,
        9.05171557e-02, -1.36558792e-01,  6.33303185e-02,  4.27629597e-01,
        6.40915540e-02, -1.28172035e+00, -1.83013459e-01, -7.00507997e-02,
        5.44852759e-01,  4.96733206e-01, -9.68722044e-02, -1.48395300e-01,
       -4.16890917e-01,  1.51538433e-01,  7.90615800e-01,  3.31627247e-01,
       -3.43250632e-01, -4.11222483e-01, -5.50639732e-01, -6.49976939e-02,
       -2.52832776e+00,  1.05404046e-01,  9.66197019e-02, -1.56427752e-01,
        2.78650344e-03,  3.78145324e-02,  6.43639510e-02, -3.28313167e-01,
        1.29115526e-01, -6.60300557e-01])

In [12]:
df['sentimento'] = df['sentimento'].map({'NEUTRAL': 0, 'POSITIVE': 1, 'NEGATIVE': -1})

In [13]:
df.head()

Unnamed: 0          autor  \
0           0     v8_capital   
1           1  winthegame_of   
2           2     marta_bego   
3           3     lmviapiana   
4           4   vanilson_dos   

                                               texto  sentimento  \
0  Confira os resultados dos nossos fundos no mês...           0   
1  A Alvarez & Marsal estará conosco no Sportainm...           0   
2  #Repost btgpactual with make_repost ・・・ Entend...           0   
3                               Minuto touro de ouro           1   
4                                   @ricktolledo Sim           0   

                                              tokens  
0  ['confira', 'o', 'resultado', 'de o', 'nosso',...  
1  ['Alvarez', 'Marsal', 'estara', 'conosco', 'sp...  
2  ['repost', 'btg', 'With', 'makerepost', 'enten...  
3                        ['minuto', 'touro', 'ouro']  
4                             ['Ricktolledo', 'sim']